adapter: postgresql
database: cactus
username: deploy
password: n3xtm0v3m3nt
host: peyote
encoding: utf8

#adapter:  postgresql
#encoding: unicode
#database: mediascape_development
#pool: 5
#username: arachman
#password:
#host: /tmp
